networks:
  matrix:
  pakinet:
    name: 'pakinet'
    external: true

services:

  # Traefik: Reverse Proxy
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - matrix
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --accessLog=true
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.web.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.letsencrypt.acme.email=${INSERIRE_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
      - --entryPoints.websecure.http.tls.certResolver=letsencrypt
      - --entryPoints.websecure.http.tls.domains[0].main=${NOME_DOMINIO}
      - --entryPoints.websecure.http.tls.domains[0].sans=*.${NOME_DOMINIO}
      - --serversTransport.insecureSkipVerify=true
      - --global.sendAnonymousUsage=false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './data/traefik/acme:/etc/traefik/acme'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${INSERIRE_EMAIL}
      - CF_API_KEY=${CF_API_KEY}

  postgres:
    container_name: 'postgres'
    image: "postgres:11.4"		
    restart: "unless-stopped"
    networks:
      - matrix
    environment:
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "${DATA_PATH}/Matrix/postgres/data:/var/lib/postgresql/data"

  synapse:    
    container_name: 'synapse'    
    image: "matrixdotorg/synapse:latest"    
    restart: "unless-stopped"    
    networks:      
      - matrix          
    environment:      
      SYNAPSE_CONFIG_DIR: "/data"      
      SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"      
    volumes:      
      - "./data/matrix/synapse:/data"      
      - "./data/matrix/bridges:/bridges:rw"    
    labels:      
      - "traefik.enable=true"      
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"      
      - "traefik.http.routers.synapse.rule=Host(`synapse.${NOME_DOMINIO}`)"      
      - "traefik.http.routers.synapse.entrypoints=websecure"      
      - "traefik.http.routers.synapse.tls.certresolver=letsencrypt"

  nginx:    
    container_name: 'nginx'    
    image: "nginx:latest"    
    restart: "unless-stopped"    
    networks:      
    - matrix     
    volumes:      
    - "./data/matrix/nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf"      
    - "./data/matrix/nginx/www:/var/www/"    
    labels:      
    - "traefik.enable=true"      
    - "traefik.http.services.matrix.loadbalancer.server.port=80"      
    - "traefik.http.routers.matrix.rule=Host(`matrix.${NOME_DOMINIO}`)"      
    - "traefik.http.routers.matrix.entrypoints=websecure"      
    - "traefik.http.routers.matrix.tls.certresolver=letsencrypt"

  coturn:
    image: "instrumentisto/coturn:latest"
    container_name: 'coturn'
    restart: "unless-stopped"
    network_mode: "host"
    volumes:
      - "./data/matrix/coturn:/etc/coturn"

  whatsapp:
    container_name: whatsapp
    image: dock.mau.dev/mautrix/whatsapp
    restart: unless-stopped
    networks:
      - matrix
    volumes:
    - ./data/matrix/bridges/whatsapp:/data

  telegram:
    container_name: telegram
    image: dock.mau.dev/mautrix/telegram
    restart: unless-stopped
    networks:
      - matrix
    volumes:
    - ./data/matrix/bridges/telegram:/data

  element:
    container_name: 'element'
    image: "vectorim/element-web:latest"
    restart: "unless-stopped"
    networks:
      - matrix
    volumes:
      - "./data/matrix/element/config.json:/app/config.json:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.element.loadbalancer.server.port=80"
      - "traefik.http.routers.element.rule=Host(`chat.${NOME_DOMINIO}`)"
      - "traefik.http.routers.element.entrypoints=websecure"
      - "traefik.http.routers.element.tls.certresolver=letsencrypt"

